// Package bridge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package bridge

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for ApprovalDecision.
const (
	ApprovalDecisionApprove ApprovalDecision = "approve"
	ApprovalDecisionDeny    ApprovalDecision = "deny"
)

// Valid indicates whether the value is a known member of the ApprovalDecision enum.
func (e ApprovalDecision) Valid() bool {
	switch e {
	case ApprovalDecisionApprove:
		return true
	case ApprovalDecisionDeny:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalStatus.
const (
	Approved ApprovalStatus = "approved"
	Denied   ApprovalStatus = "denied"
	Pending  ApprovalStatus = "pending"
)

// Valid indicates whether the value is a known member of the ApprovalStatus enum.
func (e ApprovalStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Denied:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock0Type.
const (
	Text ContentBlock0Type = "text"
)

// Valid indicates whether the value is a known member of the ContentBlock0Type enum.
func (e ContentBlock0Type) Valid() bool {
	switch e {
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock1Type.
const (
	ContentBlock1TypeToolCall ContentBlock1Type = "tool_call"
)

// Valid indicates whether the value is a known member of the ContentBlock1Type enum.
func (e ContentBlock1Type) Valid() bool {
	switch e {
	case ContentBlock1TypeToolCall:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock2Type.
const (
	ContentBlock2TypeToolResult ContentBlock2Type = "tool_result"
)

// Valid indicates whether the value is a known member of the ContentBlock2Type enum.
func (e ContentBlock2Type) Valid() bool {
	switch e {
	case ContentBlock2TypeToolResult:
		return true
	default:
		return false
	}
}

// Defines values for ContentBlock3Type.
const (
	Image ContentBlock3Type = "image"
)

// Valid indicates whether the value is a known member of the ContentBlock3Type enum.
func (e ContentBlock3Type) Valid() bool {
	switch e {
	case Image:
		return true
	default:
		return false
	}
}

// Defines values for McpTransport0Type.
const (
	Stdio McpTransport0Type = "stdio"
)

// Valid indicates whether the value is a known member of the McpTransport0Type enum.
func (e McpTransport0Type) Valid() bool {
	switch e {
	case Stdio:
		return true
	default:
		return false
	}
}

// Defines values for McpTransport1Type.
const (
	StreamableHttp McpTransport1Type = "streamable_http"
)

// Valid indicates whether the value is a known member of the McpTransport1Type enum.
func (e McpTransport1Type) Valid() bool {
	switch e {
	case StreamableHttp:
		return true
	default:
		return false
	}
}

// Defines values for ProviderType.
const (
	Anthropic ProviderType = "anthropic"
	Cohere    ProviderType = "cohere"
	Custom    ProviderType = "custom"
	DeepSeek  ProviderType = "deep_seek"
	Fireworks ProviderType = "fireworks"
	Google    ProviderType = "google"
	Groq      ProviderType = "groq"
	Mistral   ProviderType = "mistral"
	Ollama    ProviderType = "ollama"
	OpenAi    ProviderType = "open_ai"
	Together  ProviderType = "together"
	XAi       ProviderType = "x_ai"
)

// Valid indicates whether the value is a known member of the ProviderType enum.
func (e ProviderType) Valid() bool {
	switch e {
	case Anthropic:
		return true
	case Cohere:
		return true
	case Custom:
		return true
	case DeepSeek:
		return true
	case Fireworks:
		return true
	case Google:
		return true
	case Groq:
		return true
	case Mistral:
		return true
	case Ollama:
		return true
	case OpenAi:
		return true
	case Together:
		return true
	case XAi:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Assistant Role = "assistant"
	System    Role = "system"
	Tool      Role = "tool"
	User      Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ToolPermission.
const (
	ToolPermissionAllow           ToolPermission = "allow"
	ToolPermissionDeny            ToolPermission = "deny"
	ToolPermissionRequireApproval ToolPermission = "require_approval"
)

// Valid indicates whether the value is a known member of the ToolPermission enum.
func (e ToolPermission) Valid() bool {
	switch e {
	case ToolPermissionAllow:
		return true
	case ToolPermissionDeny:
		return true
	case ToolPermissionRequireApproval:
		return true
	default:
		return false
	}
}

// AbortConversationResponse Response for aborting a conversation turn.
type AbortConversationResponse struct {
	// Status Status of the abort operation.
	Status string `json:"status"`
}

// AgentConfig Configuration options for an agent.
type AgentConfig struct {
	// Compaction Configuration for conversation compaction (history summarization).
	Compaction *CompactionConfig `json:"compaction,omitempty"`

	// JsonSchema JSON schema for structured output
	JsonSchema interface{} `json:"json_schema,omitempty"`

	// MaxTokens Maximum tokens for LLM response
	MaxTokens *int32 `json:"max_tokens,omitempty"`

	// MaxTurns Maximum conversation turns
	MaxTurns *int32 `json:"max_turns,omitempty"`

	// RateLimitRpm Rate limit in requests per minute
	RateLimitRpm *int32 `json:"rate_limit_rpm,omitempty"`

	// Temperature Temperature for LLM sampling
	Temperature *float64 `json:"temperature,omitempty"`

	// MaxTasksPerConversation Maximum tasks per conversation
	MaxTasksPerConversation *int32 `json:"max_tasks_per_conversation,omitempty"`

	// MaxConcurrentConversations Maximum concurrent conversations
	MaxConcurrentConversations *int32 `json:"max_concurrent_conversations,omitempty"`

	// ToolCallsOnly Only allow tool calls, no text responses
	ToolCallsOnly *bool `json:"tool_calls_only,omitempty"`

	// DisabledTools List of tool names to completely remove from the agent.
	// Disabled tools are removed from the registry before the agent is built —
	// the LLM never sees them. Takes priority over permissions and tools allow-lists.
	DisabledTools []string `json:"disabled_tools,omitempty"`
}

// AgentDefinition Complete definition of an AI agent fetched from the control plane.
type AgentDefinition struct {
	// Config Configuration options for an agent.
	Config *AgentConfig `json:"config,omitempty"`

	// Description Human-readable description of the agent's purpose and capabilities.
	// Used in tool documentation when this agent is a subagent.
	Description *string `json:"description,omitempty"`
	Id          String  `json:"id"`

	// Integrations External integrations (e.g., GitHub, Slack, Mailchimp).
	// Each integration's actions become individual tools for the agent.
	Integrations *[]IntegrationDefinition `json:"integrations,omitempty"`

	// McpServers MCP server connections
	McpServers *[]McpServerDefinition `json:"mcp_servers,omitempty"`

	// Name Human-readable agent name
	Name string `json:"name"`

	// Permissions Per-tool permission overrides. Key = tool name, Value = permission level.
	// Tools not listed default to `Allow`.
	Permissions *map[string]ToolPermission `json:"permissions,omitempty"`

	// Provider Configuration for an LLM provider.
	Provider ProviderConfig `json:"provider"`

	// Skills Available skills
	Skills *[]SkillDefinition `json:"skills,omitempty"`

	// Subagents Nested subagent definitions
	Subagents *[]AgentDefinition `json:"subagents,omitempty"`

	// SystemPrompt System prompt for the agent
	SystemPrompt string `json:"system_prompt"`

	// Tools Agent-defined tools
	Tools *[]ToolDefinition `json:"tools,omitempty"`

	// UpdatedAt Last updated timestamp for change detection
	UpdatedAt *string `json:"updated_at,omitempty"`

	// Version Version field for change detection during sync
	Version *string `json:"version,omitempty"`

	// WebhookSecret Webhook secret for HMAC signing
	WebhookSecret *string `json:"webhook_secret,omitempty"`

	// WebhookUrl Webhook URL for event delivery
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// AgentDetailsResponse Response for getting agent details.
type AgentDetailsResponse struct {
	// ActiveConversations Number of currently active conversations.
	ActiveConversations int `json:"active_conversations"`

	// Id Agent identifier.
	Id string `json:"id"`

	// Name Agent display name.
	Name string `json:"name"`

	// SystemPrompt System prompt used by the agent.
	SystemPrompt string `json:"system_prompt"`

	// Version Agent version.
	Version *string `json:"version,omitempty"`
}

// AgentSummary Lightweight agent summary for listing endpoints.
type AgentSummary struct {
	Id String `json:"id"`

	// Name Agent name
	Name string `json:"name"`

	// Version Agent version
	Version *string `json:"version,omitempty"`
}

// ApprovalDecision The user's decision on an approval request.
type ApprovalDecision string

// ApprovalReply HTTP request body for resolving a single approval.
type ApprovalReply struct {
	// Decision The user's decision on an approval request.
	Decision ApprovalDecision `json:"decision"`
}

// ApprovalRequest A pending approval request for a tool call.
type ApprovalRequest struct {
	// AgentId Agent that initiated the tool call.
	AgentId string `json:"agent_id"`

	// Arguments Arguments passed to the tool.
	Arguments interface{} `json:"arguments"`

	// ConversationId Conversation in which the tool call occurred.
	ConversationId string `json:"conversation_id"`

	// CreatedAt When the approval request was created.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique ID for this approval request.
	Id string `json:"id"`

	// Status Status of an approval request.
	Status ApprovalStatus `json:"status"`

	// ToolCallId The LLM's tool call ID.
	ToolCallId string `json:"tool_call_id"`

	// ToolName Name of the tool being called.
	ToolName string `json:"tool_name"`
}

// ApprovalStatus Status of an approval request.
type ApprovalStatus string

// BulkApprovalReply HTTP request body for resolving multiple approvals at once.
type BulkApprovalReply struct {
	// Decision The user's decision on an approval request.
	Decision   ApprovalDecision `json:"decision"`
	RequestIds []string         `json:"request_ids"`
}

// BulkResolveApprovalsResponse Response for bulk resolving approvals.
type BulkResolveApprovalsResponse struct {
	// NotFound List of request IDs that were not found.
	NotFound []string `json:"not_found"`

	// Resolved List of request IDs that were successfully resolved.
	Resolved []string `json:"resolved"`
}

// CompactionConfig Configuration for conversation compaction (history summarization).
type CompactionConfig struct {
	// SummaryPrompt Custom system prompt for the summarization call. Uses a default if None.
	SummaryPrompt *string `json:"summary_prompt,omitempty"`

	// SummaryProvider Configuration for an LLM provider.
	SummaryProvider ProviderConfig `json:"summary_provider"`

	// TailMessages Number of recent messages to preserve verbatim after compaction.
	TailMessages *int32 `json:"tail_messages,omitempty"`

	// TokenBudget Token budget. Compaction triggers when estimated tokens exceed this.
	TokenBudget *int32 `json:"token_budget,omitempty"`
}

// ContentBlock A content block within a message.
type ContentBlock struct {
	union json.RawMessage
}

// ContentBlock0 Plain text content
type ContentBlock0 struct {
	// Text The text content
	Text string            `json:"text"`
	Type ContentBlock0Type `json:"type"`
}

// ContentBlock0Type defines model for ContentBlock.0.Type.
type ContentBlock0Type string

// ContentBlock1 defines model for .
type ContentBlock1 struct {
	// Arguments Arguments to pass to the tool
	Arguments interface{} `json:"arguments"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Name Name of the tool to call
	Name string            `json:"name"`
	Type ContentBlock1Type `json:"type"`
}

// ContentBlock1Type defines model for ContentBlock.1.Type.
type ContentBlock1Type string

// ContentBlock2 defines model for .
type ContentBlock2 struct {
	// Content The result content
	Content string `json:"content"`

	// IsError Whether the tool execution resulted in an error
	IsError *bool `json:"is_error,omitempty"`

	// ToolCallId ID of the tool call this result corresponds to
	ToolCallId string            `json:"tool_call_id"`
	Type       ContentBlock2Type `json:"type"`
}

// ContentBlock2Type defines model for ContentBlock.2.Type.
type ContentBlock2Type string

// ContentBlock3 An image attachment
type ContentBlock3 struct {
	// Data Base64-encoded image data
	Data string `json:"data"`

	// MediaType MIME type of the image
	MediaType string            `json:"media_type"`
	Type      ContentBlock3Type `json:"type"`
}

// ContentBlock3Type defines model for ContentBlock.3.Type.
type ContentBlock3Type string

// ConversationRecord A conversation with its full message history, as returned by the control plane.
type ConversationRecord struct {
	// AgentId Agent that owns this conversation.
	AgentId string `json:"agent_id"`

	// CreatedAt When the conversation was created.
	CreatedAt time.Time `json:"created_at"`
	Id        String    `json:"id"`

	// Messages Full message history.
	Messages []Message `json:"messages"`

	// Title Optional human-readable title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt When the conversation was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// CreateConversationResponse Response for creating a conversation.
type CreateConversationResponse struct {
	// ConversationId The ID of the newly created conversation.
	ConversationId string `json:"conversation_id"`

	// StreamUrl The URL to stream events from this conversation.
	StreamUrl string `json:"stream_url"`
}

// EndConversationResponse Response for ending a conversation.
type EndConversationResponse struct {
	// Status Status of the end operation.
	Status string `json:"status"`
}

// GlobalMetrics Global metrics across all agents.
type GlobalMetrics struct {
	// TotalActiveConversations Total active conversations across all agents
	TotalActiveConversations int64 `json:"total_active_conversations"`

	// TotalAgents Total number of loaded agents
	TotalAgents int `json:"total_agents"`

	// UptimeSecs Seconds since the runtime started
	UptimeSecs int64 `json:"uptime_secs"`
}

// HealthResponse Health check response.
type HealthResponse struct {
	// Status Health status - always "ok" if the server is running.
	Status string `json:"status"`

	// UptimeSecs Server uptime in seconds.
	UptimeSecs int64 `json:"uptime_secs"`
}

// HydrateConversationsRequest defines model for HydrateConversationsRequest.
type HydrateConversationsRequest struct {
	Conversations []ConversationRecord `json:"conversations"`
}

// HydrateConversationsResponse Response for hydrating conversations.
type HydrateConversationsResponse struct {
	// Hydrated Number of conversations hydrated.
	Hydrated int `json:"hydrated"`
}

// IntegrationAction A single action within an integration that an agent can invoke.
//
// Each action maps to a specific API operation on the external service.
// The control plane defines the schema and permissions for each action.
type IntegrationAction struct {
	// Description Human-readable description of what this action does.
	Description string `json:"description"`

	// Name Action identifier (e.g., "create_pull_request", "send_message").
	Name string `json:"name"`

	// ParametersSchema JSON Schema for the action's parameters.
	ParametersSchema interface{} `json:"parameters_schema"`

	// Permission Permission level for a tool within an agent.
	Permission ToolPermission `json:"permission"`
}

// IntegrationDefinition Definition of an external integration available to an agent.
//
// Each integration represents a connection to an external service (e.g., GitHub,
// Mailchimp, Slack) managed by the control plane. The control plane handles
// authentication and proxies requests to the underlying service.
type IntegrationDefinition struct {
	// Actions Available actions within this integration.
	Actions []IntegrationAction `json:"actions"`

	// Description Human-readable description of the integration.
	Description string `json:"description"`

	// Name Integration identifier (e.g., "github", "mailchimp", "slack").
	Name string `json:"name"`
}

// McpServerDefinition Definition of an MCP server that an agent connects to.
type McpServerDefinition struct {
	// Name Name of the MCP server
	Name string `json:"name"`

	// Transport Transport configuration for MCP server connections.
	Transport McpTransport `json:"transport"`
}

// McpTransport Transport configuration for MCP server connections.
type McpTransport struct {
	union json.RawMessage
}

// McpTransport0 Stdio transport — spawns a child process
type McpTransport0 struct {
	// Args Command arguments
	Args *[]string `json:"args,omitempty"`

	// Command Command to execute
	Command string `json:"command"`

	// Env Environment variables for the process
	Env  *map[string]string `json:"env,omitempty"`
	Type McpTransport0Type  `json:"type"`
}

// McpTransport0Type defines model for McpTransport.0.Type.
type McpTransport0Type string

// McpTransport1 Streamable HTTP transport — connects to an HTTP endpoint
type McpTransport1 struct {
	// Headers Additional HTTP headers
	Headers *map[string]string `json:"headers,omitempty"`
	Type    McpTransport1Type  `json:"type"`

	// Url Server URL
	Url string `json:"url"`
}

// McpTransport1Type defines model for McpTransport.1.Type.
type McpTransport1Type string

// Message A message in a conversation.
type Message struct {
	// Content Content blocks of the message
	Content []ContentBlock `json:"content"`

	// Role Role of a message sender in a conversation.
	Role Role `json:"role"`

	// Timestamp Timestamp when the message was created
	Timestamp time.Time `json:"timestamp"`
}

// MetricsResponse Complete metrics response for GET /metrics.
type MetricsResponse struct {
	// Agents Per-agent metrics
	Agents []MetricsSnapshot `json:"agents"`

	// Global Global metrics across all agents.
	Global GlobalMetrics `json:"global"`

	// Timestamp Timestamp of the snapshot
	Timestamp time.Time `json:"timestamp"`
}

// MetricsSnapshot Serializable snapshot of agent metrics for the /metrics endpoint.
type MetricsSnapshot struct {
	// ActiveConversations Currently active conversations
	ActiveConversations int64  `json:"active_conversations"`
	AgentId             String `json:"agent_id"`

	// AgentName Agent name
	AgentName string `json:"agent_name"`

	// AvgLatencyMs Average latency in milliseconds
	AvgLatencyMs float64 `json:"avg_latency_ms"`

	// FailedRequests Failed requests
	FailedRequests int64 `json:"failed_requests"`

	// InputTokens Total input tokens consumed
	InputTokens int64 `json:"input_tokens"`

	// OutputTokens Total output tokens generated
	OutputTokens int64 `json:"output_tokens"`

	// ToolCalls Total tool calls executed
	ToolCalls int64 `json:"tool_calls"`

	// TotalConversations Total conversations ever created
	TotalConversations int64 `json:"total_conversations"`

	// TotalRequests Total LLM requests
	TotalRequests int64 `json:"total_requests"`

	// TotalTokens Total tokens (input + output)
	TotalTokens int64 `json:"total_tokens"`
}

// ProviderConfig Configuration for an LLM provider.
type ProviderConfig struct {
	// ApiKey API key for authentication
	ApiKey string `json:"api_key"`

	// BaseUrl Optional custom endpoint URL
	BaseUrl *string `json:"base_url,omitempty"`

	// Model Model identifier (e.g., "gpt-4o", "claude-sonnet-4-20250514")
	Model string `json:"model"`

	// ProviderType Supported LLM provider types.
	ProviderType ProviderType `json:"provider_type"`
}

// ProviderType Supported LLM provider types.
type ProviderType string

// PushAgentsRequest defines model for PushAgentsRequest.
type PushAgentsRequest struct {
	Agents []AgentDefinition `json:"agents"`
}

// PushAgentsResponse Response for pushing agents.
type PushAgentsResponse struct {
	// Loaded Number of agents loaded.
	Loaded int `json:"loaded"`
}

// PushDiffRequest defines model for PushDiffRequest.
type PushDiffRequest struct {
	Added   []AgentDefinition `json:"added"`
	Removed []string          `json:"removed"`
	Updated []AgentDefinition `json:"updated"`
}

// PushDiffResponse Response for pushing a diff.
type PushDiffResponse struct {
	// Added Number of agents added.
	Added int `json:"added"`

	// Removed Number of agents removed.
	Removed int `json:"removed"`

	// Updated Number of agents updated.
	Updated int `json:"updated"`
}

// RemoveAgentResponse Response for removing an agent.
type RemoveAgentResponse struct {
	// Status Status of the operation.
	Status string `json:"status"`
}

// ResolveApprovalResponse Response for resolving an approval.
type ResolveApprovalResponse struct {
	// RequestId The ID of the resolved request.
	RequestId string `json:"request_id"`

	// Status Status of the resolution.
	Status string `json:"status"`
}

// Role Role of a message sender in a conversation.
type Role string

// SendMessageRequest Request body for creating a message.
type SendMessageRequest struct {
	// Content The text content to send.
	Content string `json:"content"`
}

// SendMessageResponse Response for sending a message.
type SendMessageResponse struct {
	// Status Status of the message acceptance.
	Status string `json:"status"`
}

// SkillDefinition Definition of a skill that can be activated by an agent.
type SkillDefinition struct {
	// Content Full skill prompt/instructions content
	// Can contain template variables like {{args}} that will be substituted
	Content string `json:"content"`

	// Description Description of what the skill does
	Description string `json:"description"`
	Id          String `json:"id"`

	// ParametersSchema Optional JSON Schema for structured parameters (for future use)
	ParametersSchema interface{} `json:"parameters_schema,omitempty"`

	// Title Human-readable title
	Title string `json:"title"`
}

// String defines model for String.
type String = string

// ToolCall A request to call a tool.
type ToolCall struct {
	// Arguments Arguments to pass to the tool
	Arguments interface{} `json:"arguments"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Name Name of the tool to call
	Name string `json:"name"`
}

// ToolDefinition Definition of a tool that an agent can use.
type ToolDefinition struct {
	// Description Human-readable description of what the tool does
	Description string `json:"description"`

	// Name Unique name of the tool
	Name string `json:"name"`

	// ParametersSchema JSON Schema for the tool's parameters
	ParametersSchema interface{} `json:"parameters_schema"`
}

// ToolPermission Permission level for a tool within an agent.
type ToolPermission string

// ToolResult The result of a tool execution.
type ToolResult struct {
	// Content The result content
	Content string `json:"content"`

	// IsError Whether the tool execution resulted in an error
	IsError *bool `json:"is_error,omitempty"`

	// ToolCallId ID of the tool call this result corresponds to
	ToolCallId string `json:"tool_call_id"`
}

// UpsertAgentResponse Response for upserting an agent.
type UpsertAgentResponse struct {
	// Status Status of the operation: "unchanged", "updated", or "created".
	Status string `json:"status"`
}

// BulkResolveApprovalsJSONRequestBody defines body for BulkResolveApprovals for application/json ContentType.
type BulkResolveApprovalsJSONRequestBody = BulkApprovalReply

// ResolveApprovalJSONRequestBody defines body for ResolveApproval for application/json ContentType.
type ResolveApprovalJSONRequestBody = ApprovalReply

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// PushAgentsJSONRequestBody defines body for PushAgents for application/json ContentType.
type PushAgentsJSONRequestBody = PushAgentsRequest

// UpsertAgentJSONRequestBody defines body for UpsertAgent for application/json ContentType.
type UpsertAgentJSONRequestBody = AgentDefinition

// HydrateConversationsJSONRequestBody defines body for HydrateConversations for application/json ContentType.
type HydrateConversationsJSONRequestBody = HydrateConversationsRequest

// PushDiffJSONRequestBody defines body for PushDiff for application/json ContentType.
type PushDiffJSONRequestBody = PushDiffRequest

// AsContentBlock0 returns the union data inside the ContentBlock as a ContentBlock0
func (t ContentBlock) AsContentBlock0() (ContentBlock0, error) {
	var body ContentBlock0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock0 overwrites any union data inside the ContentBlock as the provided ContentBlock0
func (t *ContentBlock) FromContentBlock0(v ContentBlock0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock0 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock0
func (t *ContentBlock) MergeContentBlock0(v ContentBlock0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock1 returns the union data inside the ContentBlock as a ContentBlock1
func (t ContentBlock) AsContentBlock1() (ContentBlock1, error) {
	var body ContentBlock1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock1 overwrites any union data inside the ContentBlock as the provided ContentBlock1
func (t *ContentBlock) FromContentBlock1(v ContentBlock1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock1 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock1
func (t *ContentBlock) MergeContentBlock1(v ContentBlock1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock2 returns the union data inside the ContentBlock as a ContentBlock2
func (t ContentBlock) AsContentBlock2() (ContentBlock2, error) {
	var body ContentBlock2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock2 overwrites any union data inside the ContentBlock as the provided ContentBlock2
func (t *ContentBlock) FromContentBlock2(v ContentBlock2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock2 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock2
func (t *ContentBlock) MergeContentBlock2(v ContentBlock2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentBlock3 returns the union data inside the ContentBlock as a ContentBlock3
func (t ContentBlock) AsContentBlock3() (ContentBlock3, error) {
	var body ContentBlock3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentBlock3 overwrites any union data inside the ContentBlock as the provided ContentBlock3
func (t *ContentBlock) FromContentBlock3(v ContentBlock3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentBlock3 performs a merge with any union data inside the ContentBlock, using the provided ContentBlock3
func (t *ContentBlock) MergeContentBlock3(v ContentBlock3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentBlock) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentBlock) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMcpTransport0 returns the union data inside the McpTransport as a McpTransport0
func (t McpTransport) AsMcpTransport0() (McpTransport0, error) {
	var body McpTransport0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpTransport0 overwrites any union data inside the McpTransport as the provided McpTransport0
func (t *McpTransport) FromMcpTransport0(v McpTransport0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpTransport0 performs a merge with any union data inside the McpTransport, using the provided McpTransport0
func (t *McpTransport) MergeMcpTransport0(v McpTransport0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMcpTransport1 returns the union data inside the McpTransport as a McpTransport1
func (t McpTransport) AsMcpTransport1() (McpTransport1, error) {
	var body McpTransport1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpTransport1 overwrites any union data inside the McpTransport as the provided McpTransport1
func (t *McpTransport) FromMcpTransport1(v McpTransport1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpTransport1 performs a merge with any union data inside the McpTransport, using the provided McpTransport1
func (t *McpTransport) MergeMcpTransport1(v McpTransport1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpTransport) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpTransport) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
