// Code generated from models.dev catalog snapshot — manually curated.
// To extend: add provider/model entries below. Each entry must reference
// a real, manually-tested model. Run `go test ./internal/registry/...` after.
//
// Inclusion policy: every model with release_date >= 2025-11 from each
// curated provider is shipped. Providers with no recent qualifying models
// (e.g. cohere, groq) fall back to their top 5 most-recent tool-call models
// so the catalog is never empty for any provider in the allow-list.
package registry

// curatedProviders is the static allow-list backing registry.Global().
// Replaces the previous //go:embed models.json approach with a hand-
// maintained Go literal so additions go through code review.
var curatedProviders = []Provider{

	{ // anthropic — Anthropic
		ID:   "anthropic",
		Name: "Anthropic",
		Doc:  "https://docs.anthropic.com/en/docs/about-claude/models",
		Models: map[string]Model{
			"claude-sonnet-4-6": {
				ID:          "claude-sonnet-4-6",
				Name:        "Claude Sonnet 4.6",
				Family:      "claude-sonnet",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08",
				ReleaseDate: "2026-02-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  3,
					Output: 15,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
			"claude-opus-4-6": {
				ID:          "claude-opus-4-6",
				Name:        "Claude Opus 4.6",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-05",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  128000,
				},
			},
			"claude-opus-4-5": {
				ID:          "claude-opus-4-5",
				Name:        "Claude Opus 4.5 (latest)",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-03-31",
				ReleaseDate: "2025-11-24",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
			"claude-opus-4-5-20251101": {
				ID:          "claude-opus-4-5-20251101",
				Name:        "Claude Opus 4.5",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-03-31",
				ReleaseDate: "2025-11-01",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
		},
	},
	{ // cohere — Cohere
		ID:   "cohere",
		Name: "Cohere",
		Doc:  "https://docs.cohere.com/docs/models",
		Models: map[string]Model{
			"command-a-translate-08-2025": {
				ID:          "command-a-translate-08-2025",
				Name:        "Command A Translate",
				Family:      "command-a",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-06-01",
				ReleaseDate: "2025-08-28",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2.5,
					Output: 10,
				},
				Limit: &Limit{
					Context: 8000,
					Output:  8000,
				},
			},
			"command-a-reasoning-08-2025": {
				ID:          "command-a-reasoning-08-2025",
				Name:        "Command A Reasoning",
				Family:      "command-a",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-06-01",
				ReleaseDate: "2025-08-21",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2.5,
					Output: 10,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  32000,
				},
			},
			"command-a-03-2025": {
				ID:          "command-a-03-2025",
				Name:        "Command A",
				Family:      "command-a",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-06-01",
				ReleaseDate: "2025-03-13",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2.5,
					Output: 10,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  8000,
				},
			},
			"c4ai-aya-vision-8b": {
				ID:          "c4ai-aya-vision-8b",
				Name:        "Aya Vision 8B",
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-03-04",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 16000,
					Output:  4000,
				},
			},
			"c4ai-aya-vision-32b": {
				ID:          "c4ai-aya-vision-32b",
				Name:        "Aya Vision 32B",
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-03-04",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 16000,
					Output:  4000,
				},
			},
		},
	},
	{ // deepseek — DeepSeek
		ID:   "deepseek",
		Name: "DeepSeek",
		API:  "https://api.deepseek.com",
		Doc:  "https://api-docs.deepseek.com/quick_start/pricing",
		Models: map[string]Model{
			"deepseek-reasoner": {
				ID:          "deepseek-reasoner",
				Name:        "DeepSeek Reasoner",
				Family:      "deepseek-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-09",
				ReleaseDate: "2025-12-01",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.28,
					Output: 0.42,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  64000,
				},
			},
			"deepseek-chat": {
				ID:          "deepseek-chat",
				Name:        "DeepSeek Chat",
				Family:      "deepseek",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-09",
				ReleaseDate: "2025-12-01",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.28,
					Output: 0.42,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  8192,
				},
			},
		},
	},
	{ // fireworks-ai — Fireworks AI
		ID:   "fireworks-ai",
		Name: "Fireworks AI",
		API:  "https://api.fireworks.ai/inference/v1/",
		Doc:  "https://fireworks.ai/docs/",
		Models: map[string]Model{
			"accounts/fireworks/models/minimax-m2p5": {
				ID:          "accounts/fireworks/models/minimax-m2p5",
				Name:        "MiniMax-M2.5",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-12",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 196608,
					Output:  196608,
				},
			},
			"accounts/fireworks/models/glm-5": {
				ID:          "accounts/fireworks/models/glm-5",
				Name:        "GLM 5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 202752,
					Output:  131072,
				},
			},
			"accounts/fireworks/models/kimi-k2p5": {
				ID:          "accounts/fireworks/models/kimi-k2p5",
				Name:        "Kimi K2.5",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01-27",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
			"accounts/fireworks/models/minimax-m2p1": {
				ID:          "accounts/fireworks/models/minimax-m2p1",
				Name:        "MiniMax-M2.1",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-12-23",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  200000,
				},
			},
			"accounts/fireworks/models/glm-4p7": {
				ID:          "accounts/fireworks/models/glm-4p7",
				Name:        "GLM 4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 198000,
					Output:  198000,
				},
			},
			"accounts/fireworks/models/deepseek-v3p2": {
				ID:          "accounts/fireworks/models/deepseek-v3p2",
				Name:        "DeepSeek V3.2",
				Family:      "deepseek",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-09",
				ReleaseDate: "2025-12-01",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.56,
					Output: 1.68,
				},
				Limit: &Limit{
					Context: 160000,
					Output:  160000,
				},
			},
			"accounts/fireworks/models/kimi-k2-thinking": {
				ID:          "accounts/fireworks/models/kimi-k2-thinking",
				Name:        "Kimi K2 Thinking",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.5,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
		},
	},
	{ // google — Google
		ID:   "google",
		Name: "Google",
		Doc:  "https://ai.google.dev/gemini-api/docs/pricing",
		Models: map[string]Model{
			"gemini-3.1-flash-lite-preview": {
				ID:          "gemini-3.1-flash-lite-preview",
				Name:        "Gemini 3.1 Flash Lite Preview",
				Family:      "gemini-flash-lite",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-03-03",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 3,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3.1-flash-image-preview": {
				ID:          "gemini-3.1-flash-image-preview",
				Name:        "Gemini 3.1 Flash Image (Preview)",
				Family:      "gemini-flash",
				Reasoning:   true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-26",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text", "image"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 60,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  32768,
				},
			},
			"gemini-3.1-pro-preview-customtools": {
				ID:          "gemini-3.1-pro-preview-customtools",
				Name:        "Gemini 3.1 Pro Preview Custom Tools",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3.1-pro-preview": {
				ID:          "gemini-3.1-pro-preview",
				Name:        "Gemini 3.1 Pro Preview",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3-flash-preview": {
				ID:          "gemini-3-flash-preview",
				Name:        "Gemini 3 Flash Preview",
				Family:      "gemini-flash",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2025-12-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 3,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3-pro-preview": {
				ID:          "gemini-3-pro-preview",
				Name:        "Gemini 3 Pro Preview",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2025-11-18",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  64000,
				},
			},
		},
	},
	{ // groq — Groq
		ID:   "groq",
		Name: "Groq",
		Doc:  "https://console.groq.com/docs/models",
		Models: map[string]Model{
			"moonshotai/kimi-k2-instruct-0905": {
				ID:          "moonshotai/kimi-k2-instruct-0905",
				Name:        "Kimi K2 Instruct 0905",
				Family:      "kimi",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-10",
				ReleaseDate: "2025-09-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  16384,
				},
			},
			"openai/gpt-oss-20b": {
				ID:          "openai/gpt-oss-20b",
				Name:        "GPT OSS 20B",
				Family:      "gpt-oss",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-08-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.075,
					Output: 0.3,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  65536,
				},
			},
			"openai/gpt-oss-120b": {
				ID:          "openai/gpt-oss-120b",
				Name:        "GPT OSS 120B",
				Family:      "gpt-oss",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-08-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.15,
					Output: 0.6,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  65536,
				},
			},
			"moonshotai/kimi-k2-instruct": {
				ID:          "moonshotai/kimi-k2-instruct",
				Name:        "Kimi K2 Instruct",
				Family:      "kimi",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-10",
				ReleaseDate: "2025-07-14",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  16384,
				},
				Status: "deprecated",
			},
			"meta-llama/llama-4-scout-17b-16e-instruct": {
				ID:          "meta-llama/llama-4-scout-17b-16e-instruct",
				Name:        "Llama 4 Scout 17B",
				Family:      "llama",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-08",
				ReleaseDate: "2025-04-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.11,
					Output: 0.34,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  8192,
				},
			},
		},
	},
	{ // mistral — Mistral
		ID:   "mistral",
		Name: "Mistral",
		Doc:  "https://docs.mistral.ai/getting-started/models/",
		Models: map[string]Model{
			"labs-devstral-small-2512": {
				ID:          "labs-devstral-small-2512",
				Name:        "Devstral Small 2",
				Family:      "devstral",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-12",
				ReleaseDate: "2025-12-09",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
			"devstral-2512": {
				ID:          "devstral-2512",
				Name:        "Devstral 2",
				Family:      "devstral",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-12",
				ReleaseDate: "2025-12-09",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.4,
					Output: 2,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"devstral-medium-latest": {
				ID:          "devstral-medium-latest",
				Name:        "Devstral 2 (latest)",
				Family:      "devstral",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-12",
				ReleaseDate: "2025-12-02",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.4,
					Output: 2,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
		},
	},
	{ // moonshotai — Moonshot AI
		ID:   "moonshotai",
		Name: "Moonshot AI",
		API:  "https://api.moonshot.ai/v1",
		Doc:  "https://platform.moonshot.ai/docs/api/chat",
		Models: map[string]Model{
			"kimi-k2.5": {
				ID:          "kimi-k2.5",
				Name:        "Kimi K2.5",
				Family:      "kimi",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"kimi-k2-thinking-turbo": {
				ID:          "kimi-k2-thinking-turbo",
				Name:        "Kimi K2 Thinking Turbo",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-08",
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.15,
					Output: 8,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"kimi-k2-thinking": {
				ID:          "kimi-k2-thinking",
				Name:        "Kimi K2 Thinking",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-08",
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.5,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
		},
	},
	{ // openai — OpenAI
		ID:   "openai",
		Name: "OpenAI",
		Doc:  "https://platform.openai.com/docs/models",
		Models: map[string]Model{
			"gpt-5.4-pro": {
				ID:          "gpt-5.4-pro",
				Name:        "GPT-5.4 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  30,
					Output: 180,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  128000,
				},
			},
			"gpt-5.4": {
				ID:          "gpt-5.4",
				Name:        "GPT-5.4",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2.5,
					Output: 15,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  128000,
				},
			},
			"gpt-5.3-codex-spark": {
				ID:          "gpt-5.3-codex-spark",
				Name:        "GPT-5.3 Codex Spark",
				Family:      "gpt-codex-spark",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  32000,
				},
			},
			"gpt-5.3-codex": {
				ID:          "gpt-5.3-codex",
				Name:        "GPT-5.3 Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.2-pro": {
				ID:          "gpt-5.2-pro",
				Name:        "GPT-5.2 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  21,
					Output: 168,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.2-codex": {
				ID:          "gpt-5.2-codex",
				Name:        "GPT-5.2 Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.2-chat-latest": {
				ID:          "gpt-5.2-chat-latest",
				Name:        "GPT-5.2 Chat",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"gpt-5.2": {
				ID:          "gpt-5.2",
				Name:        "GPT-5.2",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-codex-mini": {
				ID:          "gpt-5.1-codex-mini",
				Name:        "GPT-5.1 Codex mini",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 2,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-codex-max": {
				ID:          "gpt-5.1-codex-max",
				Name:        "GPT-5.1 Codex Max",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-codex": {
				ID:          "gpt-5.1-codex",
				Name:        "GPT-5.1 Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-chat-latest": {
				ID:          "gpt-5.1-chat-latest",
				Name:        "GPT-5.1 Chat",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"gpt-5.1": {
				ID:          "gpt-5.1",
				Name:        "GPT-5.1",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
		},
	},
	{ // openrouter — OpenRouter
		ID:   "openrouter",
		Name: "OpenRouter",
		API:  "https://openrouter.ai/api/v1",
		Doc:  "https://openrouter.ai/models",
		Models: map[string]Model{
			"openai/gpt-5.4-pro": {
				ID:          "openai/gpt-5.4-pro",
				Name:        "GPT-5.4 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  30,
					Output: 180,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  128000,
				},
			},
			"openai/gpt-5.4": {
				ID:          "openai/gpt-5.4",
				Name:        "GPT-5.4",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2.5,
					Output: 15,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  128000,
				},
			},
			"inception/mercury-2": {
				ID:          "inception/mercury-2",
				Name:        "Mercury 2",
				Family:      "mercury",
				Reasoning:   true,
				ToolCall:    true,
				ReleaseDate: "2026-03-04",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 0.75,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  50000,
				},
			},
			"openai/gpt-5.3-codex": {
				ID:          "openai/gpt-5.3-codex",
				Name:        "GPT-5.3-Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-02-24",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"google/gemini-3.1-pro-preview-customtools": {
				ID:          "google/gemini-3.1-pro-preview-customtools",
				Name:        "Gemini 3.1 Pro Preview Custom Tools",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "audio", "video", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"google/gemini-3.1-pro-preview": {
				ID:          "google/gemini-3.1-pro-preview",
				Name:        "Gemini 3.1 Pro Preview",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "audio", "video", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"anthropic/claude-sonnet-4.6": {
				ID:          "anthropic/claude-sonnet-4.6",
				Name:        "Claude Sonnet 4.6",
				Family:      "claude-sonnet",
				Reasoning:   true,
				ToolCall:    true,
				ReleaseDate: "2026-02-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  3,
					Output: 15,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  128000,
				},
			},
			"qwen/qwen3.5-plus-02-15": {
				ID:          "qwen/qwen3.5-plus-02-15",
				Name:        "Qwen3.5 Plus 2026-02-15",
				Family:      "qwen",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-04",
				ReleaseDate: "2026-02-16",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.4,
					Output: 2.4,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  65536,
				},
			},
			"qwen/qwen3.5-397b-a17b": {
				ID:          "qwen/qwen3.5-397b-a17b",
				Name:        "Qwen3.5 397B A17B",
				Family:      "qwen",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2026-02-16",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3.6,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  65536,
				},
			},
			"z-ai/glm-5": {
				ID:          "z-ai/glm-5",
				Name:        "GLM-5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-12",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 202752,
					Output:  131000,
				},
			},
			"minimax/minimax-m2.5": {
				ID:          "minimax/minimax-m2.5",
				Name:        "MiniMax M2.5",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-12",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"openrouter/aurora-alpha": {
				ID:          "openrouter/aurora-alpha",
				Name:        "Aurora Alpha",
				Reasoning:   true,
				ToolCall:    true,
				ReleaseDate: "2026-02-09",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 128000,
					Output:  50000,
				},
			},
			"anthropic/claude-opus-4.6": {
				ID:          "anthropic/claude-opus-4.6",
				Name:        "Claude Opus 4.6",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-05-30",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  128000,
				},
			},
			"openrouter/free": {
				ID:          "openrouter/free",
				Name:        "Free Models Router",
				Reasoning:   true,
				ToolCall:    true,
				ReleaseDate: "2026-02-01",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 200000,
					Output:  8000,
				},
			},
			"stepfun/step-3.5-flash:free": {
				ID:          "stepfun/step-3.5-flash:free",
				Name:        "Step 3.5 Flash (free)",
				Family:      "step",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01-29",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
			"stepfun/step-3.5-flash": {
				ID:          "stepfun/step-3.5-flash",
				Name:        "Step 3.5 Flash",
				Family:      "step",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01-29",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.1,
					Output: 0.3,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
			"arcee-ai/trinity-mini:free": {
				ID:          "arcee-ai/trinity-mini:free",
				Name:        "Trinity Mini",
				Family:      "trinity-mini",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2026-01-28",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 131072,
					Output:  131072,
				},
			},
			"arcee-ai/trinity-large-preview:free": {
				ID:          "arcee-ai/trinity-large-preview:free",
				Name:        "Trinity Large Preview",
				Family:      "trinity",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2026-01-28",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 131072,
					Output:  131072,
				},
			},
			"moonshotai/kimi-k2.5": {
				ID:          "moonshotai/kimi-k2.5",
				Name:        "Kimi K2.5",
				Family:      "kimi",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01-27",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"liquid/lfm-2.5-1.2b-thinking:free": {
				ID:          "liquid/lfm-2.5-1.2b-thinking:free",
				Name:        "LFM2.5-1.2B-Thinking (free)",
				Family:      "liquid",
				Reasoning:   true,
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2026-01-20",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 131072,
					Output:  32768,
				},
			},
			"liquid/lfm-2.5-1.2b-instruct:free": {
				ID:          "liquid/lfm-2.5-1.2b-instruct:free",
				Name:        "LFM2.5-1.2B-Instruct (free)",
				Family:      "liquid",
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2026-01-20",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 131072,
					Output:  32768,
				},
			},
			"z-ai/glm-4.7-flash": {
				ID:          "z-ai/glm-4.7-flash",
				Name:        "GLM-4.7-Flash",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-01-19",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.07,
					Output: 0.4,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  65535,
				},
			},
			"openai/gpt-5.2-codex": {
				ID:          "openai/gpt-5.2-codex",
				Name:        "GPT-5.2-Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-01-14",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"black-forest-labs/flux.2-klein-4b": {
				ID:          "black-forest-labs/flux.2-klein-4b",
				Name:        "FLUX.2 Klein 4B",
				Family:      "flux",
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2026-01-14",
				Modalities: &Modalities{
					Input:  []string{"image", "text"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 40960,
					Output:  40960,
				},
			},
			"allenai/molmo-2-8b:free": {
				ID:          "allenai/molmo-2-8b:free",
				Name:        "Molmo2 8B (free)",
				Family:      "allenai",
				Reasoning:   true,
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2026-01-09",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 36864,
					Output:  36864,
				},
			},
			"minimax/minimax-m2.1": {
				ID:          "minimax/minimax-m2.1",
				Name:        "MiniMax M2.1",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-12-23",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"bytedance-seed/seedream-4.5": {
				ID:          "bytedance-seed/seedream-4.5",
				Name:        "Seedream 4.5",
				Family:      "seed",
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2025-12-23",
				Modalities: &Modalities{
					Input:  []string{"image", "text"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 4096,
					Output:  4096,
				},
			},
			"z-ai/glm-4.7": {
				ID:          "z-ai/glm-4.7",
				Name:        "GLM-4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"google/gemini-3-flash-preview": {
				ID:          "google/gemini-3-flash-preview",
				Name:        "Gemini 3 Flash Preview",
				Family:      "gemini-flash",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2025-12-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "audio", "video", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 3,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"black-forest-labs/flux.2-max": {
				ID:          "black-forest-labs/flux.2-max",
				Name:        "FLUX.2 Max",
				Family:      "flux",
				Knowledge:   "2025-06",
				ReleaseDate: "2025-12-16",
				Modalities: &Modalities{
					Input:  []string{"image", "text"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 46864,
					Output:  46864,
				},
			},
			"xiaomi/mimo-v2-flash": {
				ID:          "xiaomi/mimo-v2-flash",
				Name:        "MiMo-V2-Flash",
				Family:      "mimo",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-12",
				ReleaseDate: "2025-12-14",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.1,
					Output: 0.3,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  65536,
				},
			},
			"nvidia/nemotron-3-nano-30b-a3b:free": {
				ID:          "nvidia/nemotron-3-nano-30b-a3b:free",
				Name:        "Nemotron 3 Nano 30B A3B (free)",
				Family:      "nemotron",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-11",
				ReleaseDate: "2025-12-14",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
			"openai/gpt-5.2-pro": {
				ID:          "openai/gpt-5.2-pro",
				Name:        "GPT-5.2 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  21,
					Output: 168,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"openai/gpt-5.2-chat": {
				ID:          "openai/gpt-5.2-chat",
				Name:        "GPT-5.2 Chat",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"openai/gpt-5.2": {
				ID:          "openai/gpt-5.2",
				Name:        "GPT-5.2",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"sourceful/riverflow-v2-standard-preview": {
				ID:          "sourceful/riverflow-v2-standard-preview",
				Name:        "Riverflow V2 Standard Preview",
				Family:      "sourceful",
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 8192,
					Output:  8192,
				},
			},
			"sourceful/riverflow-v2-max-preview": {
				ID:          "sourceful/riverflow-v2-max-preview",
				Name:        "Riverflow V2 Max Preview",
				Family:      "sourceful",
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 8192,
					Output:  8192,
				},
			},
			"sourceful/riverflow-v2-fast-preview": {
				ID:          "sourceful/riverflow-v2-fast-preview",
				Name:        "Riverflow V2 Fast Preview",
				Family:      "sourceful",
				OpenWeights: true,
				Knowledge:   "2025-06",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 8192,
					Output:  8192,
				},
			},
			"deepseek/deepseek-v3.2-speciale": {
				ID:          "deepseek/deepseek-v3.2-speciale",
				Name:        "DeepSeek V3.2 Speciale",
				Family:      "deepseek",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-07",
				ReleaseDate: "2025-12-01",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.27,
					Output: 0.41,
				},
				Limit: &Limit{
					Context: 163840,
					Output:  65536,
				},
			},
			"deepseek/deepseek-v3.2": {
				ID:          "deepseek/deepseek-v3.2",
				Name:        "DeepSeek V3.2",
				Family:      "deepseek",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-07",
				ReleaseDate: "2025-12-01",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.28,
					Output: 0.4,
				},
				Limit: &Limit{
					Context: 163840,
					Output:  65536,
				},
			},
			"tngtech/tng-r1t-chimera:free": {
				ID:          "tngtech/tng-r1t-chimera:free",
				Name:        "R1T Chimera (free)",
				Family:      "tngtech",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-07",
				ReleaseDate: "2025-11-26",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 163840,
					Output:  163840,
				},
			},
			"black-forest-labs/flux.2-pro": {
				ID:          "black-forest-labs/flux.2-pro",
				Name:        "FLUX.2 Pro",
				Family:      "flux",
				Knowledge:   "2025-06",
				ReleaseDate: "2025-11-25",
				Modalities: &Modalities{
					Input:  []string{"image", "text"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 46864,
					Output:  46864,
				},
			},
			"black-forest-labs/flux.2-flex": {
				ID:          "black-forest-labs/flux.2-flex",
				Name:        "FLUX.2 Flex",
				Family:      "flux",
				Knowledge:   "2025-06",
				ReleaseDate: "2025-11-25",
				Modalities: &Modalities{
					Input:  []string{"image", "text"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 67344,
					Output:  67344,
				},
			},
			"anthropic/claude-opus-4.5": {
				ID:          "anthropic/claude-opus-4.5",
				Name:        "Claude Opus 4.5",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-05-30",
				ReleaseDate: "2025-11-24",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  32000,
				},
			},
			"x-ai/grok-4.1-fast": {
				ID:          "x-ai/grok-4.1-fast",
				Name:        "Grok 4.1 Fast",
				Family:      "grok",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-11",
				ReleaseDate: "2025-11-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.2,
					Output: 0.5,
				},
				Limit: &Limit{
					Context: 2000000,
					Output:  30000,
				},
			},
			"google/gemini-3-pro-preview": {
				ID:          "google/gemini-3-pro-preview",
				Name:        "Gemini 3 Pro Preview",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2025-11-18",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "audio", "video", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  66000,
				},
			},
			"openrouter/sherlock-think-alpha": {
				ID:          "openrouter/sherlock-think-alpha",
				Name:        "Sherlock Think Alpha",
				Family:      "sherlock",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-11",
				ReleaseDate: "2025-11-15",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 1840000,
				},
			},
			"openrouter/sherlock-dash-alpha": {
				ID:          "openrouter/sherlock-dash-alpha",
				Name:        "Sherlock Dash Alpha",
				Family:      "sherlock",
				ToolCall:    true,
				Knowledge:   "2025-11",
				ReleaseDate: "2025-11-15",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 1840000,
				},
			},
			"openai/gpt-5.1-codex-mini": {
				ID:          "openai/gpt-5.1-codex-mini",
				Name:        "GPT-5.1-Codex-Mini",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 2,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  100000,
				},
			},
			"openai/gpt-5.1-codex-max": {
				ID:          "openai/gpt-5.1-codex-max",
				Name:        "GPT-5.1-Codex-Max",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.1,
					Output: 9,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"openai/gpt-5.1-codex": {
				ID:          "openai/gpt-5.1-codex",
				Name:        "GPT-5.1-Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"openai/gpt-5.1-chat": {
				ID:          "openai/gpt-5.1-chat",
				Name:        "GPT-5.1 Chat",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"openai/gpt-5.1": {
				ID:          "openai/gpt-5.1",
				Name:        "GPT-5.1",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"kwaipilot/kat-coder-pro:free": {
				ID:          "kwaipilot/kat-coder-pro:free",
				Name:        "Kat Coder Pro (free)",
				Family:      "kat-coder",
				ToolCall:    true,
				Knowledge:   "2025-11",
				ReleaseDate: "2025-11-10",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 256000,
					Output:  65536,
				},
			},
			"moonshotai/kimi-k2-thinking": {
				ID:          "moonshotai/kimi-k2-thinking",
				Name:        "Kimi K2 Thinking",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-08",
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.5,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
		},
	},
	{ // togetherai — Together AI
		ID:   "togetherai",
		Name: "Together AI",
		Doc:  "https://docs.together.ai/docs/serverless-models",
		Models: map[string]Model{
			"Qwen/Qwen3.5-397B-A17B": {
				ID:          "Qwen/Qwen3.5-397B-A17B",
				Name:        "Qwen3.5 397B A17B",
				Family:      "qwen",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-16",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3.6,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  130000,
				},
			},
			"MiniMaxAI/MiniMax-M2.5": {
				ID:          "MiniMaxAI/MiniMax-M2.5",
				Name:        "MiniMax-M2.5",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-12",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"zai-org/GLM-5": {
				ID:          "zai-org/GLM-5",
				Name:        "GLM-5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-11",
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 202752,
					Output:  131072,
				},
			},
			"Qwen/Qwen3-Coder-Next-FP8": {
				ID:          "Qwen/Qwen3-Coder-Next-FP8",
				Name:        "Qwen3 Coder Next FP8",
				Family:      "qwen",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2026-02-03",
				ReleaseDate: "2026-02-03",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"moonshotai/Kimi-K2.5": {
				ID:          "moonshotai/Kimi-K2.5",
				Name:        "Kimi K2.5",
				Family:      "kimi",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2026-01",
				ReleaseDate: "2026-01-27",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 2.8,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"essentialai/Rnj-1-Instruct": {
				ID:          "essentialai/Rnj-1-Instruct",
				Name:        "Rnj-1 Instruct",
				Family:      "rnj",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-10",
				ReleaseDate: "2025-12-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.15,
					Output: 0.15,
				},
				Limit: &Limit{
					Context: 32768,
					Output:  32768,
				},
			},
			"moonshotai/Kimi-K2-Thinking": {
				ID:          "moonshotai/Kimi-K2-Thinking",
				Name:        "Kimi K2 Thinking",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-07",
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.2,
					Output: 4,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
		},
	},
	{ // xai — xAI
		ID:   "xai",
		Name: "xAI",
		Doc:  "https://docs.x.ai/docs/models",
		Models: map[string]Model{
			"grok-4-1-fast-non-reasoning": {
				ID:          "grok-4-1-fast-non-reasoning",
				Name:        "Grok 4.1 Fast (Non-Reasoning)",
				Family:      "grok",
				ToolCall:    true,
				Knowledge:   "2025-07",
				ReleaseDate: "2025-11-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.2,
					Output: 0.5,
				},
				Limit: &Limit{
					Context: 2000000,
					Output:  30000,
				},
			},
			"grok-4-1-fast": {
				ID:          "grok-4-1-fast",
				Name:        "Grok 4.1 Fast",
				Family:      "grok",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-07",
				ReleaseDate: "2025-11-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.2,
					Output: 0.5,
				},
				Limit: &Limit{
					Context: 2000000,
					Output:  30000,
				},
			},
		},
	},
	{ // zai — Z.AI
		ID:   "zai",
		Name: "Z.AI",
		API:  "https://api.z.ai/api/paas/v4",
		Doc:  "https://docs.z.ai/guides/overview/pricing",
		Models: map[string]Model{
			"glm-5": {
				ID:          "glm-5",
				Name:        "GLM-5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.7-flash": {
				ID:          "glm-4.7-flash",
				Name:        "GLM-4.7-Flash",
				Family:      "glm-flash",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2026-01-19",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 200000,
					Output:  131072,
				},
			},
			"glm-4.7": {
				ID:          "glm-4.7",
				Name:        "GLM-4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.6v": {
				ID:          "glm-4.6v",
				Name:        "GLM-4.6V",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 0.9,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  32768,
				},
			},
		},
	},
	{ // zhipuai — Zhipu AI
		ID:   "zhipuai",
		Name: "Zhipu AI",
		API:  "https://open.bigmodel.cn/api/paas/v4",
		Doc:  "https://docs.z.ai/guides/overview/pricing",
		Models: map[string]Model{
			"glm-5": {
				ID:          "glm-5",
				Name:        "GLM-5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.7-flash": {
				ID:          "glm-4.7-flash",
				Name:        "GLM-4.7-Flash",
				Family:      "glm-flash",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2026-01-19",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 200000,
					Output:  131072,
				},
			},
			"glm-4.7": {
				ID:          "glm-4.7",
				Name:        "GLM-4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.6v": {
				ID:          "glm-4.6v",
				Name:        "GLM-4.6V",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 0.9,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  32768,
				},
			},
		},
	},
}
